package: easyurlrewrite
version: '1.0'
author: Benjamin Hacker
supportpage: benjamin-hacker.de
docspage: benjamin-hacker.de

page:
  title: Easy Url Rewrite

requires:
  php:
    version: '^7.0'
  redaxo: '^5.0'