package: easyurlrewrite
version: '1.0'
author: Benjamin Hacker
supportpage: benjamin-hacker.de
docspage: benjamin-hacker.de

page:
  title: 'translate:easyurlrewrite_titel'
  icon: rex-icon fa-link
  perm: admin
  subpages:
    konfiguration: { title: 'translate:easyurlrewrite_page_konfiguration_titel' }
    beschreibung: { title: 'translate:easyurlrewrite_page_beschreibung_titel' }

requires:
  php:
    version: '^7.0'
  redaxo: '^5.0'
